services:
  postgres:
    container_name: ms_postgres
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpassword
      POSTGRES_DB: pgdatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - microservices-net

  pgadmin:
    container_name: ms_pgadmin1
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - microservices-net

  mongoDb:
    container_name: ms_mongodb
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    networks:
      - microservices-net

  mongodb-express:
    container_name: ms_mongo_exp
    image: mongo-express
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_SERVER: mongoDb
    networks:
      - microservices-net

  mail-dev:
    container_name: ms_mail_dv
    image: maildev/maildev
    ports:
      - "1080:1080"
      - "1025:1032"
    networks:
      - microservices-net

volumes:
  mysql_data:
  postgres_data:
  mongo_data:
  pgadmin_data:

networks:
  microservices-net:
    driver: bridge
